apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secdemo

bases:
   - https://github.com/masauve/bgdemo/manifests/base
   - https://github.com/marouim/route-kustomize/manifests/base
patches:
  - path: patch-low-security.json
    target:
      labelSelector: "zone=low"
  - path: patch-med-security.json
    target:
      labelSelector: "zone=med"
  - path: patch-high-security.json
    target:
      labelSelector: "zone=high"
